name: Wrapup
# This workflow is triggered on push to branches that begins with a number (issue-branches)
# It's designed to support the wrapup process in thetechcollective/gh-tt GitHub CLI extension
on:
  workflow_dispatch:
  push:
    branches: 
      - '[0-9]*'

permissions:
  contents: read
  statuses: write

concurrency:
  group: "wrapup"
  cancel-in-progress: false

jobs:

  mark-pending:
    name: Statuses
    permissions:
      statuses: write
      contents: read
    uses: lakruzz/workflows/.github/workflows/mark_pending.yml@experimental
    with:
      statuses: |
        Spelling
        Markdown linter
        
  cspell_check:
    name: Spelling
    needs: mark-pending
    permissions:
      statuses: write
      contents: read
    uses: lakruzz/workflows/.github/workflows/cspell_check.yml@experimental
    with:
      config_file: cspell.json
      context: Spelling 
  
  markdown_linting:
    name: Linting
    needs: mark-pending
    permissions:
      statuses: write
      contents: read
    uses: lakruzz/workflows/.github/workflows/markdown_linter.yml@experimental
    with:
      config_file: .markdownlint-cli2.jsonc
      context: Markdown linter       

